// src/modules/framework/header/HeaderL2.vue
<template>
  <div id="buttonsL2">
    <!-- opsdetails is an alias for place, used in the original M4OPS -->
    <el-tooltip
      class="item"
      effect="light"
      content="Select from the dropdown to change whether
        the current display is one map
        with an overlay and opacity slider,
        side by side maps, or one map with a spyglass"
      placement="bottom">
      <SelectMapDisplay/>
    </el-tooltip>
    <el-tooltip
      class="item"
      effect="light"
      content="Select from the dropdown to change between
        Normal clicking (No lat/lon click),
        and getting lat/lon (in various formats)"
      placement="right-end">
      <SelectActionOnClick/>
    </el-tooltip>
  </div>
</template>

<script>
import './Header.css';
import SelectMapDisplay from './SelectMapDisplay.vue';
import SelectActionOnClick from './SelectActionOnClick.vue';

export default {
  name: 'HeaderR1',
  components: {
    SelectMapDisplay,
    SelectActionOnClick,
  },
  methods: {
    tellMe() {
      console.log('tellMe');
    },
  },
};
</script>

<style scoped>

</style>

// Old React/src/subsystems/framework/header/HeaderL2.jsx
import React from 'react';
import { Tooltip, Select } from 'antd';

import './Header.css';

const { Option } = Select;

function handleChange(value) {
  console.log(`Option chosen = ${value}`);
}

const HeaderL2 = () => (
  <div id="buttonsL">
    <Tooltip placement="right" title="Select from the dropdown to change whether the current display is one map with an overlay and opacity slider, side by side maps, or one map with a spyglass">
      <Select defaultValue="overlay" style={{ width: 120 }} onChange={handleChange} size="small">
        <Option value="overlay">Overlay</Option>
        <Option value="side by side">Side by Side</Option>
        <Option value="spyglass">Spyglass</Option>
      </Select>
    </Tooltip>

    <Tooltip placement="right" title="Select from the dropdown to change between Normal clicking (No lat/lon click), and getting lat/lon (in various formats)">
      <Select defaultValue="no" style={{ width: 170 }} onChange={handleChange} size="small">
        <Option value="no">No lat/lon click</Option>
        <Option value="m4opscsv">M4OPS lon;lat csv</Option>
        <Option value="m4opsparam">M4OPS parameters</Option>
        <Option value="csv">lat,lon csv</Option>
        <Option value="geojson">lon,lat GeoJSON</Option>
        <Option value="epsg3857">EPSG:3857 (x/y)</Option>
        <Option value="hdms">DegMinSec N/E</Option>
        <Option value="geohack">GeoHack links</Option>
      </Select>
    </Tooltip>
  </div>

);

export default HeaderL2;
