// client/src/modules/framework/header/HeaderR1.vue
<template>
  <div id="buttonsR1">

    <p class="buttons">
      <b-tooltip
        label="Return to the original One-Place Study location"
        position="is-left"
        multilined>
        <button
          class="button is-primary"
          @click="goHome()">
          <span class="icon">
            <font-awesome-icon icon="home"/>
          </span>
        </button>
      </b-tooltip>
      <b-tooltip
        label="Contact the person responsible for this study"
        position="is-left"
        multilined>
        <button
          class="button is-primary"
          @click="tellMe()">
          <span class="icon">
            <font-awesome-icon :icon="['far','envelope']"/>
          </span>
        </button>
      </b-tooltip>
      <b-tooltip
        label="Provide feedback to the person responsible for M4OPS
          within the Society for One-Place Studies"
        position="is-left"
        multilined>
        <a
          class="button is-primary"
          href="mailto:peter.cooper@one-place-studies.org?subject=M4OPS">
          <font-awesome-icon :icon="['fas','envelope']"/>
        </a>
      </b-tooltip>
      <b-tooltip
        label="See the Help documentation"
        position="is-left"
        multilined>
        <button
          class="button is-primary"
          @click="tellMe()">
          <span class="icon">
            <font-awesome-icon icon="question-circle"/>
          </span>
        </button>
      </b-tooltip>
    </p>
  </div>
</template>

<script>
import { mapGetters } from 'vuex';
import { useVuexForView } from '../../../global/constants';

// import './Header.css';

export default {
  name: 'HeaderR1',
  computed: {
    ...mapGetters([
      'homeView',
    ]),
  },
  methods: {
    tellMe() {
      console.log('tellMe');
    },
    goHome() {
      // eslint-disable-next-line max-len
      if (!useVuexForView) console.log('Remember that useVuexForView is false so GoHome button will not work');
      this.$store.dispatch('updateView', this.homeView);
    },
  },
};
</script>

<style scoped lang="scss">
  .button {margin-left: 2px};
</style>

// Old React/src/subsystems/framework/header/HeaderR1.jsx
import React from 'react';
// import { compose } from 'redux';
// import { connect } from 'react-redux';
import {
  SimpleButton,
  mappify,
} from '@terrestris/react-geo';

import GoHomeButton from '../../mapping/components/GoHomeButton';

import './Header.css';

const MappifiedGoHomeButton = mappify(GoHomeButton);

// opsdetails is an alias for place, OPSDetails was used in the original M4OPS

const tellMe = () => (
  console.log('tellMe')
);

const HeaderR1 = () => (
  <div id="buttonsR1">
    <SimpleButton
      tooltip="No props Home"
      tooltipPlacement="leftBottom"
      icon="comments"
      size="small"
      onClick={tellMe}
    />
    <MappifiedGoHomeButton
      tooltip="Return to the original One-Place Study location"
      tooltipPlacement="leftBottom"
      icon="home"
      size="small"
    />
    <SimpleButton
      tooltip="Contact the person responsible for this study"
      tooltipPlacement="leftBottom"
      icon="envelope"
      size="small"
      onClick={tellMe}
    />
    <SimpleButton
      tooltip="Provide feedback to the person responsible for M4OPS within the Society for One-Place Studies"
      tooltipPlacement="leftBottom"
      icon="comment"
      size="small"
      href="mailto:peter.cooper@one-place-studies.org?subject=M4OPS"
    />
    <SimpleButton
      tooltip="See the Help documentation"
      tooltipPlacement="leftBottom"
      icon="question-circle"
      size="small"
      onClick={tellMe}
    />
  </div>
);

export default HeaderR1;
