// src/modules/framework/header/Header.vue
<template>
  <div>
    <HeaderTitles opsdetails={{ OPSDetails }} />
    <HeaderL1 opsdetails={{ OPSDetails }} />
    <HeaderL2 />
    <HeaderR1 />
    <HeaderR2 />
  </div>
</template>

<script>
import HeaderTitles from './HeaderTitles';
import HeaderR1 from './HeaderR1';
import HeaderR2 from './HeaderR2';
import HeaderL1 from './HeaderL1';
import HeaderL2 from './HeaderL2';

export default {
  name: 'Header',
  components: {
    HeaderTitles,
    HeaderR1,
    HeaderR2,
    HeaderL1,
    HeaderL2,
  },
  props: {
    OPSDetails: {
      type: Object,
      required: true,
    },
  },
};
</script>

<style>

</style>

// src/modules/framework/header/Header.jsx
import React, { Fragment } from 'react';
import PropTypes from 'prop-types';

import HeaderTitles from './HeaderTitles';
import HeaderR1 from './HeaderR1';
import HeaderR2 from './HeaderR2';
import HeaderL1 from './HeaderL1';
import HeaderL2 from './HeaderL2';

export default function Header(props) {
  const { OPSDetails } = props;
  return (
    <Fragment>
      <HeaderTitles OPSDetails={OPSDetails} />
      <HeaderL1 OPSDetails={OPSDetails} />
      <HeaderL2 />
      <HeaderR1 />
      <HeaderR2 />
    </Fragment>
  );
}

const { object } = PropTypes;

Header.propTypes = {
  OPSDetails: object.isRequired, // eslint-disable-line react/forbid-prop-types
};
