// Old React/src/subsystems/framework/header/HeaderR2.jsx
import React from 'react';
import { SimpleButton } from '@terrestris/react-geo';
import { Input, Tooltip } from 'antd';

import './Header.css';

const { Search } = Input;

const tellMe = () => (
  console.log('Clicked') // eslint-disable-line no-console
);

const HeaderR2 = () => (
  <div id="buttonsR2">
    <Tooltip title="Text to be searched for within open features, or coordinates to go to (any format).  If blank will ask.">
      <Search
        id="textForSearchOrCoords"
        placeholder="Text or Coords"
        size="small"
        style={{ width: '80%' }}
        onSearch={value => console.log(value)} // eslint-disable-line no-console
        enterButton
      />
    </Tooltip>
    <SimpleButton
      tooltip="Make the current view of M4OPS available as a URL to copy"
      tooltipPlacement="leftBottom"
      icon="copy"
      size="small"
      onClick={tellMe}
    />
  </div>
);

export default HeaderR2;

// src/modules/framework/header/HeaderR2.vue
<template>
  <div id="buttonsR2">
    <el-form
      :inline="true"
      :model="formInline"
    >
      <el-tooltip
        class="item"
        effect="light"
        content="Text to be searched for within open features,
        or coordinates to go to (any format).  If blank will ask."
        placement="left">
        <el-form-item>
          <el-input
            v-model="formInline.textForSearchOrCoords"
            placeholder="Text or Coords to GoTo"
          />
        </el-form-item>
      </el-tooltip>
      <el-form-item>
        <el-tooltip
          class="item"
          effect="light"
          content="GoTo as specified"
          placement="left">
          <el-button
            type="primary"
            size="medium"
            icon="el-icon-search"
            @click="tellMe()"
          />
        </el-tooltip>
      </el-form-item>
      <el-form-item>
        <el-tooltip
          class="item"
          effect="light"
          content="Make the current view of M4OPS available as a URL to copy"
          placement="left">
          <el-button
            type="primary"
            size="medium"
            @click="tellMe()"
          >
            <font-awesome-icon :icon="['far','clone']"/>
          </el-button>
        </el-tooltip>
      </el-form-item>
    </el-form>
  </div>
</template>

<script>
import './Header.css';

export default {
  name: 'HeaderR2',
  data() {
    return {
      formInline: {
        textForSearchOrCoords: '',
      },
    };
  },
  methods: {
    tellMe() {
      console.log('tellMe');
    },
  },
};
</script>

<style>

</style>
