// client/src/modules/framework/headerOLD/Header.vue
<template>
  <section style="position: relative">
    <HeaderTitles :opsdetails="opsdetails" />
    <HeaderL1 :opsdetails="opsdetails" />
    <HeaderL2 />
    <HeaderR1 />
    <HeaderR2 />
  </section>
</template>

<script>
import HeaderTitles from './HeaderTitles.vue';
import HeaderR1 from './HeaderR1.vue';
import HeaderR2 from './HeaderR2.vue';
import HeaderL1 from './HeaderL1.vue';
import HeaderL2 from './HeaderL2.vue';

export default {
  name: 'Header',
  components: {
    HeaderTitles,
    HeaderR1,
    HeaderR2,
    HeaderL1,
    HeaderL2,
  },
  props: {
    opsdetails: {
      type: Object,
      default: () => ({ OPSCode: 'HcN', OPSName: 'Needingworth1' }),
    },
  },
};
</script>

<style scoped>

</style>

// src/modules/framework/header/Header.jsx
import React, { Fragment } from 'react';
import PropTypes from 'prop-types';

import HeaderTitles from './HeaderTitles';
import HeaderR1 from './HeaderR1';
import HeaderR2 from './HeaderR2';
import HeaderL1 from './HeaderL1';
import HeaderL2 from './HeaderL2';

export default function Header(props) {
  const { OPSDetails } = props;
  return (
    <Fragment>
      <HeaderTitles OPSDetails={OPSDetails} />
      <HeaderL1 OPSDetails={OPSDetails} />
      <HeaderL2 />
      <HeaderR1 />
      <HeaderR2 />
    </Fragment>
  );
}

const { object } = PropTypes;

Header.propTypes = {
  OPSDetails: object.isRequired, // eslint-disable-line react/forbid-prop-types
};
